### ISSUE TITLE
How does muxado compare with yamux?

### ISSUE THREAD

**Issue by ginkoob** [inconshreveable/muxado#13]
In search for a TCP multiplexer I've found yamux which has many similarities with muxado so I'm wondering how they compare.

http://godoc.org/github.com/hashicorp/yamux

**Comment by jbenet** [comment]
@ginkoob -- for IPFS:
- we used muxado (v1) , found some bugs then
- switched to docker/spdystream, found bugs, fixed some, then
- switched to hashicorp/yamux, so far so good, 
- want to switch to using muxado2 at some point. muxado2 is apparently faster.

Also, take a look at this module: https://github.com/jbenet/go-stream-muxer/ -- wrap them! 

We could also use this module to get common benchmarks

**Comment by jbenet** [comment]
Also, @inconshreveable and i have discussed stream muxing a lot in #ipfs on freenode. logs here: botbot.me/freenode/ipfs/ -- and eventually i want something like https://github.com/jbenet/random-ideas/issues/34

**Comment by ginkoob** [comment]
Thanks for reaching @jbenet! I ended up with yamux too.  A muxer interface would be great in the stdlib (net/muxer ?). Did you consider to make a such proposal?
