### ISSUE TITLE
zeroConfig race condition

### ISSUE THREAD

**Issue by lukechampine** [inconshreveable/muxado#18]
`zeroConfig` is a global variable, used when a `nil` config is supplied to `Server` or `Client`. `initDefaults` is then called on the config, modifying its fields. Thus there is a race condition if two goroutines simultaneously create a server or client with a `nil` config.

There are a few solutions:
1. Instantiate a new config on each call to `Server` or `Client`, instead of referencing a global variable
2. Declare a `defaultConfig` variable that holds the default values, and use that instead of `zeroConfig` when `nil` is passed
3. Use a mutex to serialize calls to `initDefaults`

Option 3 is clearly insane. Option 1 would be my choice, but I assume from `zeroConfig` that there is some motivation for reusing a global variable (efficiency?). If there is, option 2 seems like the best choice. I can open a PR for either of these.

**Comment by inconshreveable** [comment]
Fixed in a2856c9a9f02cd064b77b9ea5856b87824072123
