### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jbenet** [inconshreveable/muxado#8]
I posted these at #ipfs on irc, but this may help others too:

1. can muxado handle other transports (seems it can just wrap a net.Conn, so yes?)
2. this example https://github.com/inconshreveable/muxado#a-more-extensive-muxado-client shows making one stream per-request. is this TRTTD, or -- if we have our own per-protocol framing -- do one stream per protocol (we have roughly 4 protocols each with their own messages in ipfs atm)
3. plans to make other language implementations?

**Comment by jbenet** [comment]
More questions:

1. Is reading threadsafe? (i believe it is, but want to confirm). I'm getting odd errors where some streams get bytes out of order, so wondering if sync is not working properly.

2. What happens if streams receive data but are not read from? does muxado skip over them properly? Conversely, can deadlock occur in a sender if a reader does not read from a stream?

**Comment by inconshreveable** [comment]
1. Reading should be threadsafe. If it's not, then there's a bug.
2. If streams receive data but are not read from, their buffers will fill up until they reach the max window size (64KB). Any further attempts to send on that stream will block writing on the remote peer (their window size for that stream will go to zero). If the remote peer violates the window size and sends more data, the stream will be reset with a flow control error.

**Comment by jbenet** [comment]
thanks for the responses! one more:

- how should one listen for, and do connection garbage collection? If a connection is closed from the other side, it will not be clear to the local side.This isn't great when network pooling. I can burn a goroutine on `Wait()`, but it may be useful to expose:

```Go
type Session interface {
  IsClosed() bool
}
```

So that we can check it whenever a stream is closed, or sweeping periodically.

**Comment by inconshreveable** [comment]
`Accept()` exits with an error when the session closes (and only when the session closes). You're probably already waiting on `Accept()` so that would probably be easiest that way.

The wip branch has different error codes for failures. It's possible to call `GetError()` on any failed stream operation and see if you get the code `SessionClosed`.

I've been thinking about whether it's a good idea to remove Wait() entirely since you can get that same signal from `Accept()`. The tradeoff being: 1) you might not care about handling incoming streams 2) you won't get notification of session termination until you've accepted all incoming streams in the accept queue. 3) you'll have to make separate call to pull out the all of the error information around why the session closed, which would be a new API, something like:

```go
type Session interface {
   GetCloseInfo() (isClosed bool, localError error, remoteError error, remoteDebug []byte)
}
```

Alternatively I'm considering a callback API like:
```go
OnClose(handler func(Session, localError, remoteError error, remoteDebug []byte))
```

**Comment by jbenet** [comment]
> Accept() exits with an error when the session closes (and only when the session closes). You're probably already waiting on Accept() so that would probably be easiest that way.

Ah, perfect. `Accept() exits with an error when the session closes and only when the session closes` maybe should be added to Accept's doc. I can send a PR if you want me too-- dev branch?

> The wip branch has different error codes for failures. It's possible to call GetError() on any failed stream operation and see if you get the code SessionClosed.

Oh sweet. looks like this is all handled by your `wip`.

> I've been thinking about whether it's a good idea to remove Wait() entirely since you can get that same signal from Accept(). The tradeoff being: 1) you might not care about handling incoming streams 2) you won't get notification of session termination until you've accepted all incoming streams in the accept queue. 3) you'll have to make separate call to pull out the all of the error information around why the session closed, which would be a new API, something like:


I think these three add up to `Wait` (or something like it) staying.

> Alternatively I'm considering a callback API like:

I think it's nice to be able to wait on things as channels:

```Go
// I wish sync.WaitGroup.Wait was:
<-wg.Wait()
```

Actually, you might like this... It's a WIP, of mine: 
https://godoc.org/github.com/jbenet/goprocess (sorry, godoc is still WIP). 
I'll fwd some relevant discussion by email, but basically, it lets you do
things like the following. And sorry, if you dont use godoc.org/code.google.com/p/go.net/context -- this is may be totally out of left field.

```Go

type Session struct {
  Process Process()
}

func NewSession(...) *Session {
  s := &Session{}
  s.Process = goprocess.WithTeardown(s.teardown) // called **exactly once**
  return s
}

func Close() error {
  return s.Process.Close() // can be called many times. sync.Once semantics.
}

...


s := NewSession(...)

s.Close() // blocks until s is fully closed.
<-s.Closing() // chan closed after s has begun to close
<-s.Closed() // chan closed after s has finished teardown

// can spin off "child" workers:
// * when parents close, they call child.Close()
// * parents wait for children to be fully <-Closed() before calling own teardown

// spin off async worker to accept new streams.
s.Go(func(child goprocess.Process) {
  for {
    stream, err := s.Accept() 
    if err != nil {
      return // child closes automatically after func returns
    }
    
    select {
    case <-child.Closing(): // parent (s.Process) has called .Close() on child
      return
    default:
    }
    
    s.Go(handleStream) 
    // handleStream is a subprocess, so can know when to shutdown.
  }
})


// child procs (like go.net/context.Context):
func newStream(sess *Session) *Stream {
  stream := *Stream{}
  stream.Process: s.WithTeardown(s.teardown) // exactly once for free.

  // sess adds stream as child:
  // * when told to Close, sess will Close child stream
  // * sess waits on stream to fully close before tearing down itself.
  sess.Process.AddChild(stream.Process)
  
  return stream
}
```

Note: in the typical "`net` and channels dont mix" fashion, 
session must amke sure that the `Accept()` call above unblocks when
begginning to Close, but before witing on its children:

```Go
func (s *Session) Accept() (*Stream, error) {

  ...

  select {
  case <-s.Process.Closing():
    return nil, ErrClosing
  case s, more := <-s.newStreams:
    if !more {
      return nil, ErrClosing
    }
    return s, nil
  }
  return stream
}

```

**Comment by inconshreveable** [comment]
Very cool. goprocess reminds me a bit of neimeyer's tomb and the other "supervisor trees" packages implemented for Go.

I prefer callbacks to channels in public APIs because:
    a) callbacks are faster (and your API customer may care about performance)
    b) it is easy to build out support for channel waiting on top of a callback primitive

```go
sess := muxado.NewSession(...)
done := make(chan struct{})
sess.OnClose(func() {
    close(done)
})
```

It's fine to have both with the channel method being a convenience, of course.

Improving the docs is on my list before I publish the WIP branch. Adding that doc for Accept() will be part of it.

**Comment by inconshreveable** [comment]
Finally discovered where I got the idea to add Wait() from:
