### ISSUE TITLE
use too much memory with big window size.

### ISSUE THREAD

**Issue by bronze1man** [inconshreveable/muxado#9]
I need to use this protocol with a 100ms and 10MB/s link.
So I set the window size to `10MB*0.1*2 = 2MB`.
In this code https://github.com/inconshreveable/muxado/blob/master/proto/buffer/circular.go#L38
muxado need 4MB memory for each connect.
I think this buffer should expend as needed, and has a max number which is window size.

**Comment by inconshreveable** [comment]
This is fixed in the wip branch.

The inbound buffer now uses `bytes.Buffer` until I can 1) hack together a growable-ring buffer and 2) prove that it actually helps performance.

**Comment by inconshreveable** [comment]
fixed in wip and merged
